services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: crypto_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

    environment:
      - MONGO_URI=mongodb://mongo:27017/crypto
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecretkey123
      - STRIPE_SECRET_KEY=sk_test_51Hkv2kGETpcP6ndNX7BE2xIyofmsBUGXK2yFyxI7S7FOnfABvGbCzKnoif39gJHBlb9NixcbcmurVimVJ3KoorFG00SoLPy2w6
      - STRIPE_WEBHOOK_SECRET=whsec_mc5Gr65owVHoKUDwiTN02aHH37V5RPiB

  mongo:
    image: mongo:7
    container_name: crypto_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: crypto_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes

  nginx:
    image: nginx:stable-alpine
    container_name: crypto_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/ppchu.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/ppchu.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - app
    restart: always

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml -ingester.wal-enabled=true -ingester.wal-dir=/tmp/loki/wal
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    restart: always

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - nginx-logs:/var/log/nginx
    command: -config.file=/etc/promtail/config.yaml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://ppchu.com/logs
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  mongodb_data:
  redis_data:
  grafana-data:
  nginx-logs:
