services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: crypto_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/crypto
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecretkey123
      - STRIPE_SECRET_KEY=sk_test_51Hkv2kGETpcP6ndNX7BE2xIyofmsBUGXK2yFyxI7S7FOnfABvGbCzKnoif39gJHBlb9NixcbcmurVimVJ3KoorFG00SoLPy2w6
      - STRIPE_WEBHOOK_SECRET=whsec_mc5Gr65owVHoKUDwiTN02aHH37V5RPiB

  mongo:
    image: mongo:7
    container_name: crypto_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: crypto_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes

  nginx:
    image: nginx:stable-alpine
    container_name: crypto_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-logs:/var/log/nginx
    depends_on:
      - app
    restart: always

volumes:
  mongodb_data:
  redis_data:
  nginx-logs:
