services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/crypto
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecretkey123
      - STRIPE_SECRET_KEY=sk_test_51Hkv2kGETpcP6ndNX7BE2xIyofmsBUGXK2yFyxI7S7FOnfABvGbCzKnoif39gJHBlb9NixcbcmurVimVJ3KoorFG00SoLPy2w6
      - STRIPE_WEBHOOK_SECRET=whsec_mc5Gr65owVHoKUDwiTN02aHH37V5RPiB

    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
      - nginx-logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  redis_dev_data:
  nginx-logs:
