server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx-prod
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          env: prod
          __path__: /var/log/nginx/access.prod.log

  - job_name: nginx-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          env: dev
          __path__: /var/log/nginx/access.dev.log
